### ISSUE TITLE
Habilitar pruebas de unidad para el flujo de development

### ISSUE THREAD

**Issue by eamazaj** [DinersDigital/ms-core-archetype#14]
https://github.com/DinersDigital/ms-core-archetype/blob/cea72504611da235df3411afbf173e451a88b06c/Jenkinsfile#L173

**Comment by skilledboy** [comment]
Todos los tipos de test(Unit Test, Code Test, Kiuwan Test) se ejecutaran  en los ambientes de develop y qa(release)
