### ISSUE TITLE
Versionar Dokerfile de la imagen tools

### ISSUE THREAD

**Issue by eamazaj** [DinersDigital/ms-core-archetype#21]
https://github.com/DinersDigital/ms-core-archetype/blob/d872fb68d2e5324428e94b83ae87b811fad23a6f/Jenkinsfile#L21

**Comment by skilledboy** [comment]
@eamazaj  @christmo  en este repo dejo versionado el proyecto que se uso para la imagen tools
https://github.com/diners-prodigio/image-tools
Favor clonar para el grupo de diners
