### ISSUE TITLE
Para que usan el CRON JOB de OpenShift?

### ISSUE THREAD

**Issue by christmo** [DinersDigital/ms-core-archetype#23]
Donde está la plantilla de esto?

![Screenshot from 2021-04-14 12-36-24](https://user-images.githubusercontent.com/291154/114755547-63de6b80-9d1f-11eb-9159-faeec8ec7875.png)

**Comment by skilledboy** [comment]
@christmo este cron fue eliminado cuando hablamos en la demostración del pipeline el miercoles, ya que no se usa y era parte de pruebas iniciales.
